[[protocols]]
name = "lg_tv"
protocol = "nec"
variant = "nec32"
[protocols.scancodes]
0x400 = "KEY_CHANNELUP"
0x401 = "KEY_CHANNELDOWN"
0x402 = "KEY_VOLUMEUP"
0x403 = "KEY_VOLUMEDOWN"
0x406 = "KEY_RIGHT"
0x407 = "KEY_LEFT"
0x408 = "KEY_POWER"
0x409 = "KEY_MUTE"
0x40b = "KEY_INPUT"
0x40f = "KEY_TV"
0x410 = "KEY_0"
0x411 = "KEY_1"
0x412 = "KEY_2"
0x413 = "KEY_3"
0x414 = "KEY_4"
0x415 = "KEY_5"
0x416 = "KEY_6"
0x417 = "KEY_7"
0x418 = "KEY_8"
0x419 = "KEY_9"
0x41e = "KEY_FAVORITES"
0x41a = "KEY_BACKSPACE"
0x430 = "KEY_MODE"
0x440 = "KEY_UP"
0x441 = "KEY_DOWN"
0x443 = "KEY_HOME"
0x445 = "KEY_MENU"
0x428 = "KEY_BACK"
0x444 = "KEY_ENTER"
0x44c = "KEY_MINUS"
0x45b = "KEY_EXIT"
0x461 = "KEY_BLUE"
0x463 = "KEY_YELLOW"
0x471 = "KEY_GREEN"
0x472 = "KEY_RED"
0x479 = "KEY_RATIO"
0x48e = "KEY_FASTFORWARD"
0x48f = "KEY_REWIND"
0x4aa = "KEY_INFO"
0x4b0 = "KEY_PLAY"
0x4b1 = "KEY_STOP"
0x4ba = "KEY_PAUSE"
