[[protocols]]
name = "roku"
protocol = "nec"
variant = "nec32"
[protocols.scancodes]
0xeac703 = "KEY_HOME_DOWN"
0xeac706 = "KEY_SLING_DOWN"
0xeac708 = "KEY_VUDU_DOWN"
0xeac70f = "KEY_VOLUMEUP_DOWN"
0xeac710 = "KEY_VOLUMEDOWN_DOWN"
0xeac717 = "KEY_POWER_DOWN"
0xeac719 = "KEY_UP_DOWN"
0xeac71e = "KEY_LEFT_DOWN"
0xeac720 = "KEY_MUTE_DOWN"
0xeac72a = "KEY_ENTER_DOWN"
0xeac72d = "KEY_RIGHT_DOWN"
0xeac733 = "KEY_DOWN_DOWN"
0xeac734 = "KEY_REWIND_DOWN"
0xeac74b = "KEY_AMAZON_DOWN"
0xeac74c = "KEY_PLAY_DOWN"
0xeac74d = "KEY_HULU_DOWN"
0xeac752 = "KEY_NETFLIX_DOWN"
0xeac755 = "KEY_FASTFORWARD_DOWN"
0xeac761 = "KEY_INFO_DOWN"
0xeac766 = "KEY_BACK_DOWN"
0xeac76c = "KEY_HBONOW_DOWN"
0xeac778 = "KEY_BACKSPACE_DOWN"
0xeac77f = "KEY_RDIO_DOWN"
0xeac783 = "KEY_HOME"
0xeac786 = "KEY_SLING"
0xeac788 = "KEY_VUDU"
0xeac78f = "KEY_VOLUMEUP"
0xeac790 = "KEY_VOLUMEDOWN"
0xeac797 = "KEY_POWER"
0xeac799 = "KEY_UP"
0xeac79e = "KEY_LEFT"
0xeac7a0 = "KEY_MUTE"
0xeac7aa = "KEY_ENTER"
0xeac7ad = "KEY_RIGHT"
0xeac7b3 = "KEY_DOWN"
0xeac7b4 = "KEY_REWIND"
0xeac7cb = "KEY_AMAZON"
0xeac7cc = "KEY_PLAY"
0xeac7cd = "KEY_HULU"
0xeac7d2 = "KEY_NETFLIX"
0xeac7d5 = "KEY_FASTFORWARD"
0xeac7e1 = "KEY_INFO"
0xeac7e6 = "KEY_BACK"
0xeac7ec = "KEY_HBONOW"
0xeac7f8 = "KEY_BACKSPACE"
0xeac7ff = "KEY_RDIO"
