[[protocols]]
name = "squeezebox"
protocol = "nec"
variant = "nec32"
[protocols.scancodes]
0x6e00 = "KEY_VOLUMEDOWN"
0x6e01 = "KEY_VOLUMEUP"
0x6e02 = "KEY_POWER"
0x6e03 = "KEY_REWIND"
0x6e04 = "KEY_PAUSE"
0x6e05 = "KEY_FORWARD"
0x6e06 = "KEY_ADD"
0x6e07 = "KEY_UP"
0x6e08 = "KEY_PLAY"
0x6e09 = "KEY_LEFT"
0x6e0b = "KEY_RIGHT"
0x6e0d = "KEY_DOWN"
0x6e0f = "KEY_1"
0x6e10 = "KEY_2"
0x6e11 = "KEY_3"
0x6e12 = "KEY_4"
0x6e13 = "KEY_5"
0x6e14 = "KEY_6"
0x6e15 = "KEY_7"
0x6e16 = "KEY_8"
0x6e17 = "KEY_9"
0x6e18 = "KEY_FAVORITES"
0x6e19 = "KEY_0"
0x6e1a = "KEY_SEARCH"
0x6e1b = "KEY_SHUFFLE"
0x6e1c = "KEY_REPEAT"
0x6e1d = "KEY_SLEEP"
0x6e1e = "KEY_PLAYING"
0x6e1f = "KEY_SIZE"
0x6e20 = "KEY_BRIGHTNESS"
